name: Keep Vercel App Warm (Multi-Endpoint)

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch: # optional manual trigger from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping multiple endpoints
        run: |
          endpoints=(
            "https://hemp.itslitto.com/api/ping"
            "https://hemp.itslitto.com/login"
            "https://hemp.itslitto.com/"
          )

          for url in "${endpoints[@]}"; do
            echo "Pinging $url"
            curl -s --max-time 10 "$url" || echo "Failed to ping $url"
          done
